---
- name: Install NFS client
  ansible.builtin.apt:
    name: nfs-common

- name: Mount NFS share
  ansible.posix.mount:
    path: "{{ mount_path }}"
    src: "{{ nfs_server }}:{{ nfs_path }}"
    fstype: nfs
    opts: "{{ mount_options }}"
    state: mounted
  ignore_errors: "{{ error_ok }}"